import {DEFAULT_KEY, SNAIL_KEY, MASOCHIST_KEY} from './keyCorrespondance';

export const LETTER_SCORE_MAPPING = {
    ' ': 1,
    'e': 1,
    't': 1,
    'a': 1,
    'o': 1,
    'i': 1,
    'n': 1,
    's': 1,
    'h': 1,
    'r': 1,
    'd': 2,
    'l': 2,
    'c': 2,
    'u': 2,
    'm': 2,
    'w': 2,
    'f': 2,
    'g': 2,
    'y': 2,
    'p': 2,
    'b': 2,
    'v': 2,
    'k': 2,
    'j': 3,
    'x': 3,
    'q': 3,
    'z': 3,
    'é': 4,
    'è': 4,
    'à': 4,
    'ç': 4,
    'ê': 5,
    'ë': 5,
    'ä': 5,
    'ô': 5,
    'ö': 5,
    'ï': 5,
    'î': 5,
    'û': 5,
    'ü': 5,
    'ÿ': 5,
    'æ': 6,
    'á': 6,
    'ã': 6,
    'å': 6,
    'ā': 6,
    'ę': 6,
    'ė': 6,
    'ē': 6,
    'ì': 6,
    'í': 6,
    'į': 6,
    'ī': 6,
    'œ': 6,
    'ò': 6,
    'ó': 6,
    'õ': 6,
    'ø': 6,
    'ō': 6,
    'ù': 6,
    'ú': 6,
    'ū': 6,
};

export const LETTER_COMBO_MAPPING = {
    0: {
        [DEFAULT_KEY]: 1,
        [SNAIL_KEY]: 1,
        [MASOCHIST_KEY]: 1,
    },
    10: {
        [DEFAULT_KEY]: 2,
        [SNAIL_KEY]: 1,
        [MASOCHIST_KEY]: 3,
    },
    30: {
        [DEFAULT_KEY]: 4,
        [SNAIL_KEY]: 2,
        [MASOCHIST_KEY]: 6,
    },
    60: {
        [DEFAULT_KEY]: 8,
        [SNAIL_KEY]: 4,
        [MASOCHIST_KEY]: 12,
    },
    100: {
        [DEFAULT_KEY]: 16,
        [SNAIL_KEY]: 8,
        [MASOCHIST_KEY]: 24,
    },
};
